default_platform(:android)

# add all ENV properties
# run in terminal with 'fastlane buildDev'

platform :android do

  scheme = nil
  output = nil
  variant = nil
  type = nil

  desc "Build Dev"
  lane :buildDev do
    scheme = "Development"
    output = "development"
    variant = "debug"
    type = "Debug"
    distribute
  end

  desc "Build Production"
  lane :buildProd do
    scheme = "Production"
    output = "production"
    variant = "release"
    type = "Release"
    distribute
  end

  desc "Build bundle and Create APK for #{scheme}"
      lane :distribute do
          gradle(
               task: "clean assembleDebug",
               print_command: false,
               properties: {
                       "android.injected.signing.store.file" => "/home/runner/work/github-user-android/github-user-android/keys/githubuser.jks",
                       "android.injected.signing.store.password" => "githubuser",
                       "android.injected.signing.key.alias" => "githubuser",
                       "android.injected.signing.key.password" => "githubuser",
                       "android.injected.version.code" => 50,
                       "android.injected.version.name" => "1.1.0",
                     }
          )
      end
end
